services:
  - type: web
    name: chess-academy-backend
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: chess-academy-backend
          property: port
    healthCheckPath: /health
    plan: free
    region: oregon
    rootDir: .
    buildFilter:
      paths:
        - backend/**